name: "CI - Terraform  Infrastructure"

permissions:
  pull-requests: write
  contents: read

on:
  push:
    branches:
      - "feature/**"

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
jobs:
  ci:
    name: ci
    uses: rhoribe/test/.github/workflows/01-terraform-aws-ci.yaml@feature/test
    secrets: inherit
  
  pr: 
    name: pr
    uses: rhoribe/test/.github/workflows/00-open-pr.yaml@feature/test
    needs: ci
    
