name: "CI - Terraform  Infrastructure"

permissions:
  pull-requests: write
  contents: read

on:
  push:
    branches:
      - "main"

jobs:
  ci:
    name: ci
    uses: rhoribe/test/.github/workflows/01-terraform-aws-ci.yaml@feature/test
    secrets: inherit
  
  pr: 
    name: pr
    uses: rhoribe/test/.github/workflows/00-open-pr.yaml@feature/test
    needs: ci

  costs: 
    name: costs
    uses: rhoribe/test/.github/workflows/02-terraform-aws-costs.yaml@feature/test
    needs: [pr,ci]
    secrets: inherit