name: "Costs - Terraform  Infrastructure"

permissions:
  pull-requests: write
  contents: read

on:
  pull_request:

jobs:
  costs: 
    name: costs
    uses: rhoribe/test/.github/workflows/02-terraform-aws-costs.yaml@feature/test
    secrets: inherit

    